### ISSUE TITLE
build error for me

### ISSUE THREAD

**Issue by bobwatcherx** [mahmoodsaed/FletToAPK#1]
i try you code
ho to solve this sir 

code

```
name: Build Flet APK

on:
  workflow_dispatch:
    inputs:
      flet_version:
        description: 'Flet version'
        required: true
        default: '0.22.1'
      android_sdk_version:
        description: 'Android SDK version'
        required: true
        default: '33'
      android_ndk_version:
        description: 'Android NDK version'
        required: true
        default: '24.0.8215888'
      flutter_version:
        description: 'Flutter version'
        required: true
        default: '3.3.9'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flet
        run: pip install flet

      - name: Install Pillow
        run: pip install pillow
        
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl xz-utils

      - name: Install Flutter
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sL https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_$flutter_version-stable-linux-x86_64.tar.xz | tar -xJ
          sudo mv flutter /usr/local/flutter
          sudo chown -R $USER:$USER /usr/local/flutter
          export PATH="/usr/local/flutter/bin:$PATH"
          flutter doctor

      - name: Install Android SDK and NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk-$android_sdk_version
          sudo apt-get install -y android-ndk-$android_ndk_version

      - name: Build APK
        run: |
          python counter.py
          flet build android
          flet package android
```

![Screenshot 2024-05-15 101649](https://github.com/mahmoodsaed/FletToAPK/assets/52072811/4884f925-fded-4a87-9518-68639b7ae012)
